name: KLEPON
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  image_picker: ^0.8.7+3
  get_storage: ^2.1.1
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.2.1 # Tambahkan paket
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/bukit.png
    - assets/images/manten.png
    - assets/images/nilo.png
    - assets/images/ponggok.png
    - assets/images/candi.png
    - assets/images/sigedang.png
    - assets/images/tjokro.png
    - assets/images/reddoorz.png
    - assets/images/pondok.png
    - assets/images/perdana.png
    - assets/images/koito.png
    - assets/images/galak.png
    - assets/images/kopi.png
    - assets/images/lava.png

    - assets/images/gopay.jpg
    - assets/images/ovo.jpg
    - assets/images/dana.jpg
    - assets/images/shopeepay.jpg